### ISSUE TITLE
[Feature request]: Improve output video quality if input video contains rotated people/faces

### ISSUE THREAD

**Issue by suphamster** [s0md3v/roop#201] opened 2023-05-31 18:03 UTC
For now quality is average. I'm talking about input video not image since there are some ppl don't like to read properly what I say.

**Comment by henryruhs** [comment] 2023-05-31 19:06
Duplicate of https://github.com/s0md3v/roop/issues/146

**Closed by henryruhs** 2023-05-31 19:06 UTC
