### ISSUE TITLE
[Feature] specify who needs to change faces

### ISSUE THREAD

**Issue by SpenserCai** [s0md3v/roop#621] opened 2023-06-26 03:47 UTC
Can specify who needs to change faces
In multiplayer mode, a photo of the person who needs to be changed can be uploaded, and during each frame processing, the person who needs to be changed can be found through comparison

**Comment by henryruhs** [comment] 2023-06-26 05:47
Duplicate of https://github.com/s0md3v/roop/issues/117

**Closed by henryruhs** 2023-06-26 05:47 UTC
