### ISSUE TITLE
Target specific face in the group of faces

### ISSUE THREAD

**Issue by imomin** [s0md3v/roop#334] opened 2023-06-05 01:34 UTC
With your current implementation, it is swapping the first face in the frame.  What if someone wants to swap a specific face. Example, if you refer to [this picture](https://raw.githubusercontent.com/nttstar/insightface-resources/master/images/t1.jpg). If I want to swap 3rd face from the left then it doesn't.

It would be nice to have 3 options:
1)  Source Face (eg. Elon Musk)
2) Target Face (eg. Ross)
3) Media to apply on. (eg. Above image)

get_face_single would have additional "target_face" parameter
``` get_face_single(frame,traget_face) ```

Upon executing the code if it can identify the target face in the frame as a positive face and replace it with the source face.

**Comment by henryruhs** [comment] 2023-06-05 07:38
Duplicate of https://github.com/s0md3v/roop/issues/117

**Closed by henryruhs** 2023-06-05 07:38 UTC
