### ISSUE TITLE
Got leaked memory, mac m1

### ISSUE THREAD

**Issue by greentornado** [s0md3v/roop#375] opened 2023-06-07 08:37 UTC
**Describe the bug**

I got an error when running 
/Users/hai/.pyenv/versions/miniconda3-3.9-23.1.0-1/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [x ] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [x ] Mac

**Screenshots**

**Sanity Check**
- [x ] I have the latest code from the github repository
- [x ] I have followed the installation guide

**Comment by kttyt** [comment] 2023-06-07 11:22
I've alse got multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
but I'm used gpu-vendor apple

**Comment by sphuff** [comment] 2023-06-07 13:01
I'm also seeing with python version `3.10.6`

**Comment by henryruhs** [comment] 2023-06-07 15:34
Duplicate of https://github.com/s0md3v/roop/issues/321

**Closed by henryruhs** 2023-06-07 15:34 UTC
