### ISSUE TITLE
Crash while processing a video

### ISSUE THREAD

**Issue by petr-vysotskiy** [s0md3v/roop#422] opened 2023-06-10 17:10 UTC
**Describe the bug**
roop crashes with the following error:
```
/Users/peter/.pyenv/versions/3.9.16/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**To Reproduce**
Launch with the following parameters:
python run.py --gpu-vendor=apple --cpu-cores=30

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [x] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [x] Mac

**Sanity Check**
- [x] I have the latest code from the github repository
- [x] I have followed the installation guide

**Comment by henryruhs** [comment] 2023-06-10 17:19
Duplicate of https://github.com/s0md3v/roop/issues/321

**Closed** 2023-06-10 17:19 UTC
