### ISSUE TITLE
High GPU usage, exceeding 30G

### ISSUE THREAD

**Issue by coding-alt** [s0md3v/roop#352] opened 2023-06-05 16:56 UTC
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: /onnxruntime_src/onnxruntime/core/framework/bfc_arena.cc:368 void* onnxruntime::BFCArena::AllocateRawInternal(size_t, bool, onnxruntime::Stream*, bool, onnxruntime::WaitNotificationFn) Failed to allocate memory for requested buffer of size 37748736

cuda11.8
torch 2.0
system:ubuntu 20.0.4

**Comment by henryruhs** [comment] 2023-06-05 16:56
Hey, on the main branch?

**Comment by henryruhs** [comment] 2023-06-05 17:10
Duplicate of https://github.com/s0md3v/roop/issues/321

**Closed by henryruhs** 2023-06-05 17:10 UTC

**Comment by coding-alt** [comment] 2023-06-06 01:52
> 
def swap_face_img(source_img, target_img):
    print(source_img, target_img)

    print("detecting face...")
    test_face = get_face(cv2.imread(source_img))
    if not test_face:
        print("\n[WARNING] No face detected in source image. Please try with another one.\n")
        return

    print("detecting face in target image...")
    if face_check(target_img) > 0.7:
        quit("[WARNING] Unable to determine location of the face in the target. Please make sure the target isn't wearing clothes matching to their skin.")

    output_img = '/tmp/' + uuid.uuid4().hex + '.png'

    print("swapping face...")
    process_img(source_img, target_img, output_img)
    print("swap successful!")

    return output_img
    
    
    
Based on the implementation of run.py, it encapsulates a calling method. 
Because I use this project under linux, I cannot use the gui
